<?xml version="1.0" encoding="utf-8"?><Database Name="Clinica" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-BSS49D9R\SQLEXPRESS;Initial Catalog=Clinica;Integrated Security=True" SettingsObjectName="Clinica.Properties.Settings" SettingsPropertyName="ClinicaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Citas" Member="Citas">
    <Type Name="Citas">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="ID_Medico" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Secretario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Paciente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Citas_Historial_Medico" Member="Historial_Medico" ThisKey="id" OtherKey="ID_Cita" Type="Historial_Medico" />
      <Association Name="Pacientes_Citas" Member="Pacientes" ThisKey="ID_Paciente" OtherKey="id" Type="Pacientes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Administrador" Member="Administrador">
    <Type Name="Administrador">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Rut" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Especialidades" Member="Especialidades">
    <Type Name="Especialidades">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Especialidad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Especialidades_Medicos" Member="Medicos" ThisKey="id" OtherKey="ID_Especialidad" Type="Medicos" />
    </Type>
  </Table>
  <Table Name="dbo.Historial_Medico" Member="Historial_Medico">
    <Type Name="Historial_Medico">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Diagnostico" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Alergias" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ID_Cita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Citas_Historial_Medico" Member="Citas" ThisKey="ID_Cita" OtherKey="id" Type="Citas" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Medicos" Member="Medicos">
    <Type Name="Medicos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Rut" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ID_Especialidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Disponible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID_Telefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Especialidades_Medicos" Member="Especialidades" ThisKey="ID_Especialidad" OtherKey="id" Type="Especialidades" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Telefonos_Medicos" Member="Telefonos" ThisKey="ID_Telefono" OtherKey="id" Type="Telefonos" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.Pacientes" Member="Pacientes">
    <Type Name="Pacientes">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Rut" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pacientes_Citas" Member="Citas" ThisKey="id" OtherKey="ID_Paciente" Type="Citas" />
    </Type>
  </Table>
  <Table Name="dbo.Secretarios" Member="Secretarios">
    <Type Name="Secretarios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Rut" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Telefonos" Member="Telefonos">
    <Type Name="Telefonos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numero_Tel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numero_Tel_OP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Telefonos_Medicos" Member="Medicos" ThisKey="id" OtherKey="ID_Telefono" Type="Medicos" />
    </Type>
  </Table>
</Database>